Repository gardener/gardener-extension-networking-calico, pull requests merged in 2020-10, with the labels that each got.

#52 Typha and kube-controller have proper tolerations
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#54 Vendor g/g@v1.11.1
  Makefile
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/modules.txt
Labels: area/networking, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#56 Enhance extension's chart values
  Dockerfile
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/gardener-extension-networking-calico/templates/vpa.yaml
  charts/gardener-extension-networking-calico/values.yaml
  example/controller-registration.yaml
Labels: area/documentation, area/robustness, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#57 add priority class for extension pods
  charts/gardener-extension-networking-calico/templates/_helpers.tpl
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/gardener-extension-networking-calico/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#58 Delete shoot managed resources during migration
  go.mod
  go.sum
  pkg/controller/actuator_migrate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/cmd/options.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/managed_resource.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/utils.go
  vendor/github.com/gardener/gardener/hack/check-generate.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/scaling.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/types.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/operation/common/managedresources.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/pkg/utils/managedresources/managedresources.go
  vendor/github.com/gardener/gardener/test/framework/gardener_utils.go
  vendor/github.com/gardener/gardener/test/framework/gardenerframework.go
  vendor/github.com/gardener/gardener/test/framework/seedregistrationframework.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/modules.txt
Labels: area/control-plane-migration, area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
