Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-06, with the labels that each got.

#86 update calico version to 1.19.1
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#87 Update calico-cpa
  charts/images.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#88 Only use secondary bin dir during cni installation
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#89 Exclude calico-typha container images from binary scanning
  charts/images.yaml
Labels: area/networking, kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/xs

#83 landscaper integration
  .ci/component_descriptor
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
Labels: area/delivery, kind/enhancement, lifecycle/rotten, needs/changes, needs/ok-to-test, needs/review, size/m, status/author-action

#90 Update README.md
  README.md
Labels: needs/ok-to-test, needs/review, size/xs

#92 Enabled automatic management of the kubeconfig used by the cni operations
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#93 Unify container image tag in Makefile
  Makefile
Labels: needs/ok-to-test

#96 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
