Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-07, with the labels that each got.

#97 Removed support for very old kubernetes releases in terms of older priority class api versions.
  charts/gardener-extension-networking-calico/templates/_helpers.tpl
  charts/gardener-extension-networking-calico/templates/priorityclass.yaml
  charts/utils-templates/templates/_versions.tpl
  example/controller-registration.yaml
Labels: area/networking, kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/xs

#99 Fix wrong entry in manifest for landscaper deployment
  .landscaper/blueprint/deploy-executions.yaml
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#98 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/gardener-extension-networking-calico/values.yaml
  cmd/gardener-extension-networking-calico/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#91 Extend makefile for landscaper local dev
  Makefile
  hack/create-installation.sh
  hack/environment.sh
  hack/generate-cd.sh
Labels: area/dev-productivity, kind/enhancement, lifecycle/stale, needs/ok-to-test, reviewed/lgtm, size/m

#100 drop support for k8s <v1.15.0
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/utils-templates/templates/_versions.tpl
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#102 remove bidirectional mount propagation
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#105 Disallow running without kube-proxy.
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#95 Added validating admission webhook for calico networking extension.
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  charts/gardener-extension-admission-calico/.helmignore
  charts/gardener-extension-admission-calico/Chart.yaml
  charts/gardener-extension-admission-calico/charts/application/Chart.yaml
  charts/gardener-extension-admission-calico/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-calico/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-calico/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-calico/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-calico/charts/application/values.yaml
  charts/gardener-extension-admission-calico/charts/runtime/Chart.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/secret-cert.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-calico/charts/runtime/values.yaml
  charts/gardener-extension-admission-calico/templates/_helpers.tpl
  charts/gardener-extension-admission-calico/values.yaml
  cmd/gardener-extension-admission-calico/app/app.go
  cmd/gardener-extension-admission-calico/main.go
  example/30-validatingwebhookconfiguration.yaml
  example/admission-calico-certs/tls.crt
  example/admission-calico-certs/tls.key
  pkg/admission/cmd/options.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/cmd/factory.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/cmd/options.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/handler.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/handler_shootclient.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/mutator.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/registration.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/remote_addr.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/utils.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/validator.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/do-not-merge, reviewed/lgtm, size/xl
