Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-12, with the labels that each got.

#126 Increase memory limit for typha
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#127 update memory limit for typha to 2Gi
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#128 Increased memory limit of calico-kube-controllers to 300Mi
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#129 Increased memory limit of calico-kube-controllers to 300Mi
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#131 fix autoscaling for node-cpva
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/bug, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#130 add autoscaling for memory to tyhpa deployment
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#132 update calico to v3.21.2
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#134 Update felix log level
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#133 Use default log level info for calico-nodes and set revisionhistorylimit.
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#135 Change typha rollout strategy to ensure typha availability.
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#136 Set log level of typha to info
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
