Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-02, with the labels that each got.

#69 Updated Calico to v3.17.2
  charts/images.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#68 Add security context to install-cni container
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#71 Update .gitignore file to ignore GitGuardian
  .gitignore
Labels: area/networking, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
