Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-11, with the labels that each got.

#121 Vendor gardener/gardener@v1.33.1
  .github/ISSUE_TEMPLATE/support.md
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/support.md
  vendor/github.com/gardener/gardener/extensions/pkg/controller/cluster.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdog.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdogfactory.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/context.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/ownerchecker.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/ownercheckerfactory.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/watchdogmanager.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/network/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/shoot.go
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_cloudprofile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_cloudprofile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_cloudprofile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/finalizers.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/patch.go
  vendor/github.com/gardener/gardener/pkg/extensions/owner.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/deploy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/interfaces.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/logging/kube_rbac_proxy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/phase.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/types.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/utils/gardener/shoot.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/kubernetes.go
  vendor/github.com/gardener/gardener/pkg/utils/version/version.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#122 Fixed networking provider config api version.
  README.md
Labels: area/documentation, area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#124 update calico to v3.21.0
  charts/gardener-extension-networking-calico/templates/rbac.yaml
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-caliconodestatuses.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipreservations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networkpolicies.yaml
  charts/internal/calico/templates/kube-controller/clusterrole-calico-kube-controllers.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l

#123 Add docforge manifest
  .docforge/manifest.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#125 Update to calico v3.21.1
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
