Repository gardener/gardener-extension-networking-calico, pull requests merged in 2021-03, with the labels that each got.

#72 Configure calico to use autodetection method cidr
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, size/xs

#73 Check if networkConfig.IPv4 is set
  pkg/controller/actuator_reconcile.go
Labels: needs/ok-to-test

#75 Add vpa for calico-kube-controllers
  charts/internal/calico/templates/kube-controller/vpa.yaml
  charts/internal/calico/values.yaml
  pkg/charts/charts_test.go
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
