Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-07, with the labels that each got.

#190 Update cpa to v1.8.5
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#191 Update calico to v3.23.2
  charts/images.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#193 Support k8s version < 1.21
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgpconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#194 fix images
  charts/images.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#192 Adapt the deployment priorityClassName according to the gardener documentation
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/gardener-extension-networking-calico/templates/priorityclass.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#196 Do not run calico-kube-controllers in privileged mode
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#183 Drop `PodDisruptionBudget` for `calico-kube-controllers`
  charts/internal/calico/templates/kube-controller/pod-disruption-budget.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#186 Add MaxAllowed for VPA objects
  charts/gardener-extension-admission-calico/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-calico/values.yaml
  charts/gardener-extension-networking-calico/templates/vpa.yaml
  charts/gardener-extension-networking-calico/values.yaml
  charts/internal/calico/templates/kube-controller/vpa.yaml
  charts/internal/calico/templates/node/vpa.yaml
  charts/internal/calico/templates/typha/vpa.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, area/auto-scaling

#198 Build Multi-Arch Images 📦
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
