Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-01, with the labels that each got.

#138 `make generate` for the year change
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/v1alpha1/zz_generated.defaults.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
Labels: area/networking, needs/ok-to-test, needs/review, size/xs

#139 Increased cpu limit of calico typha and memory limit of the calico autoscalers.
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s

#140 Fixed calico autoscaling, typha rollout strategy, calico log level, increased typha cpu limits, increased calico autoscaler memory limits, and increased revision history limit.
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/v1alpha1/zz_generated.defaults.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s

#141 Update to calico 3.21.3
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
Labels: area/networking, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#142 remove cpu cpva autoscaling for calico-node
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#144 update to calico v3.21.4
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#143 Remove autoscaling of cpu requests for calico-node from cpva.
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#145 Fixed vpa for calico-kube-controllers being applied even if the target was not deployed
  charts/internal/calico/templates/kube-controller/vpa.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
