Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-08, with the labels that each got.

#200 Remove install-requirement and use tools.mk
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#202 update calico to v3.23.3
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#203 Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled
  charts/internal/calico/templates/kube-controller/clusterrole-garden-psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/rolebinding-garden-psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/clusterrole-gardener-psp-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node-cpva/psp-gardener-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/rolebinding-gardener-psp-node-cpva.yaml
  charts/internal/calico/templates/node/clusterrole-garden-psp-calico.yaml
  charts/internal/calico/templates/node/psp-calico.yaml
  charts/internal/calico/templates/node/rolebinding-garden-psp-calico.yaml
  charts/internal/calico/templates/typha-cpha/clusterrole-gardener-psp-typha-cpha.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpha/psp-gardener-typha-cpa.yaml
  charts/internal/calico/templates/typha-cpha/rolebinding-gardener-psp-typha-cpa.yaml
  charts/internal/calico/templates/typha-cpva/clusterrole-gardener-psp-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/rolebinding-gardener-psp-typha-cpva.yaml
  charts/internal/calico/templates/typha/clusterrole-garden-psp-calico-typha.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  charts/internal/calico/templates/typha/psp-gardener-calico-typha.yaml
  charts/internal/calico/templates/typha/rolebinding-garden-psp-calico-typha.yaml
  charts/internal/calico/values.yaml
  pkg/charts/charts_test.go
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
Labels: area/open-source, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#204 Default seccomp profile for calico components
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node-cpva/psp-gardener-node-cpva.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/node/psp-calico.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpha/psp-gardener-typha-cpa.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  charts/internal/calico/templates/typha/psp-gardener-calico-typha.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#206 Update cluster-proportional-autoscaler image
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#209 Add an option to run calico-node in non-privileged mode
  charts/gardener-extension-networking-calico/templates/configmap.yaml
  charts/gardener-extension-networking-calico/values.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/values.yaml
  cmd/gardener-extension-networking-calico/app/app.go
  cmd/gardener-extension-networking-calico/main.go
  docs/usage-as-operator.md
  example/00-componentconfig.yaml
  example/controller-registration.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/charts/charts_test.go
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
  pkg/features/features.go
  vendor/k8s.io/component-base/featuregate/OWNERS
  vendor/k8s.io/component-base/featuregate/feature_gate.go
  vendor/modules.txt
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m
