Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-11, with the labels that each got.

#219 Update API Core version in examples to core.gardener.cloud/v1beta1
  docs/usage-as-end-user.md
  example/20-network.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#221 Clean up scheduler.alpha.kubernetes.io/critical-pod annotations
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#218 Configure SecurityContext for Calico-Kube-Controller
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#223 Update calico to v3.24.5
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgpconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-blockaffinities.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-caliconodestatuses.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-clusterinformations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworksets.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-hostendpoints.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamblocks.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamconfigs.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamhandles.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipreservations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-kubecontrollersconfiguration.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networksets.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
