Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-05, with the labels that each got.

#177 Update container base images (golang/alpine) to newer releases.
  Dockerfile
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#178 Update to Calico v3.22.2
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamblocks.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-kubecontrollersconfiguration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#179 Fixed check if kube-proxy can be disabled.
  pkg/admission/validator/shoot.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#180 add liveness and readiness probe to admission webhook
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/values.yaml
  cmd/gardener-extension-admission-calico/app/app.go
  vendor/github.com/gardener/gardener/pkg/healthz/default.go
  vendor/github.com/gardener/gardener/pkg/healthz/healthz.go
  vendor/github.com/gardener/gardener/pkg/healthz/informer.go
  vendor/github.com/gardener/gardener/pkg/healthz/periodic.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#181 Allow projected volumes for calico-node, calico-typha and calico-kube-controllers
  charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/psp-gardener-node-cpva.yaml
  charts/internal/calico/templates/node/psp-calico.yaml
  charts/internal/calico/templates/typha-cpha/psp-gardener-typha-cpa.yaml
  charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  charts/internal/calico/templates/typha/psp-gardener-calico-typha.yaml
Labels: area/networking, kind/bug, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#182 [release-v1.24] Automated cherry pick of #181: Allow projected volumes for calico-node, calico-typha and calico-kube-controllers
  charts/internal/calico/templates/kube-controller/psp-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/psp-gardener-node-cpva.yaml
  charts/internal/calico/templates/node/psp-calico.yaml
  charts/internal/calico/templates/typha-cpha/psp-gardener-typha-cpa.yaml
  charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  charts/internal/calico/templates/typha/psp-gardener-calico-typha.yaml
Labels: area/networking, kind/bug, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#184 Increase memory limit of calico kube-controllers as new release requires more memory on large clusters
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
