Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-02, with the labels that each got.

#146 Update calico typha cpva to not autoscale at the same step size for c…
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#147 Improve the calico scrape configuration
  charts/internal/calico-monitoring/templates/calico-monitoring-config.yaml
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#148 Update calico to v3.22.0
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#149 Update calico typha cpva to not autoscale at the same step size for calico typha cpva and calico node cpva.
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
Labels: area/networking, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, size/xs

#151 Increase timeouts of readiness/liveness probes of calico node to handle overload situations.
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#150 Removed support for outdated kubernetes releases.
  charts/images.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgpconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-blockaffinities.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-caliconodestatuses.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-clusterinformations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworksets.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-hostendpoints.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamblocks.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamconfigs.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipamhandles.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ippools.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-ipreservations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-kubecontrollersconfiguration.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networksets.yaml
  charts/internal/calico/templates/kube-controller/clusterrole-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/pod-disruption-budget.yaml
  charts/internal/calico/templates/node/configmap-calico-config.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/l

#152 Allow typha deployment updates even on single node clusters.
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#153 Allow typha deployment updates even on single node clusters.
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: reviewed/ok-to-test
