Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-03, with the labels that each got.

#155 Removed cpu limits for calico-node, calico-typha, and the calico autoscalers and increased the memory limits
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/s

#156 Removed cpu limits for calico-node, calico-typha, and the calico autoscalers and increased the memory limits.
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/s

#158 update calico cpu limits to 1000 for calico node and calico typha
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: needs/ok-to-test

#159 update calico cpu limits to 1000 for calico node and calico typha
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: needs/ok-to-test

#162 Adapt calico-kube-controllers to remove cpu limit and increase readiness/liveness probe timeout.
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#163 update to calico v3.22.1
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#165 Increase memory limit of calico-kube-controllers and restrict its vpa to request scaling.
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/vpa.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#164 Increase memory limit of calico-kube-controllers and restrict its vpa to request scaling.
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/kube-controller/vpa.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#166 Remove cpu limits for calico node and typha
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#168 Remove cpu limits for calico node and typha
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#169 Adapted memory limits to real world experience.
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#170 Adapted memory limits to real world experience.
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#172 Add support for sa token volume projection in admission charts
  charts/gardener-extension-admission-calico/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-calico/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-admission-calico/values.yaml
  docs/deployment.md
Labels: needs/ok-to-test, reviewed/lgtm
