Repository gardener/gardener-extension-networking-calico, pull requests merged in 2022-04, with the labels that each got.

#174 Add vertical pod autoscalers for calico-node and calico-typha.
  charts/internal/calico/templates/node/vpa.yaml
  charts/internal/calico/templates/typha/vpa.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#175 Switch vertical pod autoscaler to v1.
  charts/gardener-extension-admission-calico/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-networking-calico/templates/vpa.yaml
  charts/internal/calico/templates/kube-controller/vpa.yaml
  charts/internal/calico/templates/node/vpa.yaml
  charts/internal/calico/templates/typha/vpa.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#157 Update manifest.yaml
  .docforge/manifest.yaml
Labels: needs/ok-to-test, needs/review, size/xs
