Repository gardener/gardener-extension-networking-calico, pull requests merged in 2023-05, with the labels that each got.

#266 Induce component version using ldflags
  Dockerfile
  Makefile
  cmd/gardener-extension-admission-calico/app/app.go
  cmd/gardener-extension-admission-calico/main.go
  cmd/gardener-extension-networking-calico/app/app.go
  cmd/gardener-extension-networking-calico/main.go
  vendor/k8s.io/component-base/version/verflag/verflag.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#267 Adapt `NetworkPolicy`s
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/charts/runtime/templates/service.yaml
  charts/gardener-extension-networking-calico/templates/service.yaml
  example/controller-registration.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#268 Update cluster-proportional-autoscaler to v1.8.8
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#269 Update golang to 1.20.4
  Dockerfile
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#270 Fixed broken links - 2023.05
  docs/shoot_overlay_network.md
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
