Repository gardener/gardener-extension-networking-calico, pull requests merged in 2023-08, with the labels that each got.

#285 Allow propagating pod routes to nodes without overlay network
  charts/internal/calico/templates/ippool/ippool.yaml
  hack/api-reference/calico.md
  pkg/apis/calico/types_network.go
  pkg/apis/calico/v1alpha1/types_network.go
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/api-change, kind/enhancement, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#289 Add support for projected volume kubeconfig
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/values.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#291 Add known limitations in conjunction with NodeLocalDNS.
  docs/usage/usage.md
Labels: area/documentation, area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
