Repository gardener/gardener-extension-networking-calico, pull requests merged in 2023-02, with the labels that each got.

#235 Update typha dashboard
  charts/internal/calico-monitoring/calico-typha-dashboard.json
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#234 Revert "landscaper integration (#83)"
  .ci/component_descriptor
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#238 Revert "Merge pull request #91 from achimweigel/landscaper-local-dev-test2"
  Makefile
  hack/create-installation.sh
  hack/environment.sh
  hack/generate-cd.sh
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#231 Drop nodeSelector and tolerations from Shoot System Components
  README.md
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  charts/internal/calico/values.yaml
  pkg/charts/charts_test.go
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/cleanup, needs/ok-to-test, needs/changes, needs/review, size/m

#240 Downport purge landscaper remains
  .ci/component_descriptor
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
Labels: kind/api-change, needs/ok-to-test, reviewed/lgtm, size/m

#241 Fix source network address translation to infrastructure dns with regards to pod security policy.
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#242 Add responsibles for components and cleanup old snapshot versions.
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#236 Mark calico-node as node-critical component
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#244 update docs
  README.md
  docs/usage-as-end-user.md
  example/20-network.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
