Repository gardener/gardener-extension-networking-calico, pull requests merged in 2023-10, with the labels that each got.

#286 Add autoscaling configuration option to select autoscaler
  charts/internal/calico/templates/node-cpva/clusterrole-gardener-psp-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/clusterrole-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/clusterrolebinding-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node-cpva/psp-gardener-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/rolebinding-gardener-psp-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/serviceaccount-node-cpva.yaml
  charts/internal/calico/templates/node/vpa.yaml
  charts/internal/calico/templates/typha-cpva/clusterrole-gardener-psp-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/clusterrole-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/clusterrolebinding-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/psp-gardener-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/rolebinding-gardener-psp-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/serviceaccount-typha-cpva.yaml
  charts/internal/calico/templates/typha/vpa.yaml
  charts/internal/calico/values.yaml
  docs/usage/usage.md
  example/20-network.yaml
  hack/api-reference/calico.md
  pkg/apis/calico/types_network.go
  pkg/apis/calico/v1alpha1/types_network.go
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, ok-to-test

#304 update calico to version 3.26.2
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#308 update calico to v3.26.3
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#294 Introduce the use of central manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#312 Don't wait for MR to get deleted in case of force-delete
  pkg/controller/actuator_delete.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
