Repository gardener/gardener-extension-networking-calico, pull requests merged in 2024-07, with the labels that each got.

#437 [admission] Add `priorityClassName`
  charts/gardener-extension-admission-calico/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-calico/values.yaml
Labels: area/networking, area/robustness, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#440 update calico to v3.27.4
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#445 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, area/networking, kind/enhancement, needs/ok-to-test, needs/review, reviewed/lgtm, size/s
