Repository gardener/gardener-extension-networking-calico, pull requests merged in 2024-09, with the labels that each got.

#464 Add support for static resource requests
  charts/internal/calico/templates/kube-controller/vpa.yaml
  charts/internal/calico/templates/node-cpva/clusterrole-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/clusterrolebinding-node-cpva.yaml
  charts/internal/calico/templates/node-cpva/configmap-node-vertical-autoscaling.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node-cpva/serviceaccount-node-cpva.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/node/vpa.yaml
  charts/internal/calico/templates/typha-cpva/clusterrole-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/clusterrolebinding-typha-cpva.yaml
  charts/internal/calico/templates/typha-cpva/configmap-typha-vertical-autoscaling.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/serviceaccount-typha-cpva.yaml
  charts/internal/calico/templates/typha/deployment-calico-typha.yaml
  charts/internal/calico/templates/typha/vpa.yaml
  charts/internal/calico/values.yaml
  docs/usage/usage.md
  hack/api-reference/calico.md
  pkg/apis/calico/types_network.go
  pkg/apis/calico/v1alpha1/types_network.go
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/charts/charts_test.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, needs/changes, reviewed/ok-to-test, size/l, area/auto-scaling

#486 Fix networkConfig for IPv6.
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#489 Adjust resource requests and autoscaling of `calico-node` side car containers.
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/node/vpa.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#491 Remove VPA `(min|max)Allowed` settings.
  charts/gardener-extension-admission-calico/values.yaml
  charts/gardener-extension-networking-calico/values.yaml
  charts/internal/calico/templates/kube-controller/vpa.yaml
  charts/internal/calico/templates/typha/vpa.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, area/auto-scaling

#492 Update calico to v3.28.2
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-felixconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-globalnetworkpolicies.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-networkpolicies.yaml
  charts/internal/calico/templates/node/clusterrole-calico-node.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
