Repository gardener/gardener-extension-networking-calico, pull requests merged in 2024-10, with the labels that each got.

#501 Use host-local ipam for IPv6.
  pkg/charts/charts_test.go
  pkg/charts/utils.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#503 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  hack/sast.sh
  pkg/apis/config/loader/loader.go
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, area/compliance

#504 Add SAST logs to OCM component descriptor
  .ci/pipeline_definitions
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/compliance

#506 set correct iptables rules when using ipv6
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
