Repository gardener/gardener-extension-networking-calico, pull requests merged in 2025-08, with the labels that each got.

#692 Fix a bug that prevented Prometheus from storing Calico metrics
  charts/internal/calico-monitoring/templates/scrapeconfig-felix.yaml
  charts/internal/calico-monitoring/templates/scrapeconfig-typha.yaml
Labels: area/monitoring, kind/bug, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#695 Add permissions to release job.
  .github/workflows/release.yaml
Labels: area/networking, kind/bug, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#697 Change permissions in release workflow
  .github/workflows/release.yaml
Labels: area/networking, kind/bug, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#707 import release-commit for verify-job
  .github/workflows/build.yaml
Labels: area/delivery, kind/bug, size/XS, cla: yes
