Repository gardener/gardener-extension-networking-calico, pull requests merged in 2025-07, with the labels that each got.

#673 export empty GOPATH
  .github/workflows/build.yaml
Labels: area/networking, kind/bug, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#674 specify go verison file
  .github/workflows/build.yaml
Labels: area/networking, kind/bug, size/XS, cla: yes, reviewed/ok-to-test

#676 disable caching for go dependencies
  .github/workflows/build.yaml
Labels: area/networking, kind/enhancement, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#682 REUSE: Convert DEP5 to `REUSE.toml`
  .reuse/dep5
  REUSE.toml
Labels: area/open-source, kind/enhancement, size/M, cla: yes, approved, lgtm, reviewed/ok-to-test
