Repository gardener/gardener-extension-networking-calico, pull requests merged in 2025-02, with the labels that each got.

#577 fix permissions of calico-kube-controllers
  charts/internal/calico/templates/kube-controller/clusterrole-calico-kube-controllers.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, size/xs

#584 Make source network address translation configurable in IPv6 scenario.
  charts/internal/calico/templates/ippool/ippool.yaml
  charts/internal/calico/values.yaml
  hack/api-reference/calico.md
  pkg/apis/calico/types_network.go
  pkg/apis/calico/v1alpha1/types_network.go
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/charts/charts_test.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/s

#585 Make source network address translation configurable in IPv6 scenario.
  charts/internal/calico/templates/ippool/ippool.yaml
  charts/internal/calico/values.yaml
  hack/api-reference/calico.md
  pkg/apis/calico/types_network.go
  pkg/apis/calico/v1alpha1/types_network.go
  pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/calico/zz_generated.deepcopy.go
  pkg/charts/charts_test.go
  pkg/charts/utils.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm

#592 Make extension ports configurable via helm values
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/gardener-extension-networking-calico/templates/service.yaml
  charts/gardener-extension-networking-calico/values.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#590 Update pipeline_definitions to golang:1.24.0
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#576 Forbid privilege escalations
  charts/gardener-extension-admission-calico/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-networking-calico/templates/deployment.yaml
  charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml
  charts/internal/calico/templates/node-cpva/deployment-calico-node-vertical-autoscaler.yaml
  charts/internal/calico/templates/node/daemonset-calico-node.yaml
  charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml
  charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml
  example/controller-registration.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/compliance

#599 Update to calico-v3.29.2
  charts/internal/calico/templates/custom-resource-definition/crd-bgpconfigurations.yaml
  charts/internal/calico/templates/custom-resource-definition/crd-bgppeers.yaml
  charts/internal/calico/templates/kube-controller/clusterrole-calico-kube-controllers.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#600 Update pipeline_definitions
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
